name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run checks in the build environment
        run: docker build --target test --tag rtnt:test --file Containerfile .
      - name: Build runtime image
        run: docker build --tag rtnt:${{ github.sha }} --file Containerfile .
      - name: Smoke test runtime image
        run: docker run --rm rtnt:${{ github.sha }} --help
