name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build CI environment
        run: docker build --target development --tag rtnt-ci:${{ github.sha }} --file Containerfile .
      - name: Run checks in CI environment
        run: |
          docker run --rm rtnt-ci:${{ github.sha }} sh -c '
            cargo build --locked --verbose &&
            cargo test --locked --all-targets --verbose &&
            cargo test --locked --doc &&
            cargo clippy --locked --all-targets --all-features -- -D warnings -W clippy::pedantic
          '
      - name: Build runtime image
        run: docker build --tag rtnt:${{ github.sha }} --file Containerfile .
      - name: Smoke test runtime image
        run: docker run --rm rtnt:${{ github.sha }} --help
